name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2025.1
        with: